### ISSUE TITLE
Should we experiment with high powered systems

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers#42]
Hi Kirk, 

Megan ran into a performance problem. Well, she made a spatial query that would have returned 43,000 stream segments with about 10,000 data points each. That might overload any web request. However, since we have pagination it should be able to return the data in small chunks. However, that also timed out in our case because their is not enough memory to make the initial query and then chop away from it. 

I think at some point we need a decision how much performance we should offer and where we should make compromises. The problem with that is the already very complex description how to use the data. 

What it comes down to is whether we should invest money to test a cloud based solution at least for a very short term to learn about their characteristics.

Maybe we should meet on this.
Falk

**Comment by kklausmeyer** [comment]
Hi Falk-

Thanks for tracking down the root of Megan's issue.  I think her request is typical of the type of requests we will get, such as "I want to download all the data for the Central Valley" or "I want all of the data for the last 20 years for the entire dataset".  We can try to get people to minimize their requests, but people will still push the system to the limits.

In terms of investment, we have $10,000 allocated to hosting fees this year in the water team budget.  So I hope that will give us some room to at least experiment with enough memory to meet these demands.  

I would be happy to meet to discuss this in more detail-  this is the whole point of the MVP-  get it out there and see when it how it needs to be improved.

**Comment by postfalk** [comment]
Thx, Kirk. Let's discuss. I am thinking of DynamoDB, Amazon Aurora, or MongoDB Atlas. Here some pro and cons:

**MongoDB Atlas** would need the lowest amount of work it would be just configuration and data transfer to get up and running. Performance would be a function of the underlying infrastructure. Hard to predict.

**Amazon Aurora** is a database service by Amazon that is build to be compatible with the most common RDBMS like PostgreSQL. The performance would be up to 10x that of the original product with the same infrastructure. Would require a rebuild, but in relatively comfortable territory. It would allow for complete random access. Performance would be a function of underlying infrastructure (money).

**DynamoDB** is Amazons very own NoSQL database system and the performance is virtually unlimited. You pay for the amount of data (high in our case) and the throughput (low in our case). However, there is still a limit of what can be hold in the memory of the application but that could be chopped down at the DB side of thing.

I think it will not be possible to make an unlimited download size. However, it should be easier for the user to get a loop that returns chunks that can processed within 10 secs max.

**Comment by postfalk** [comment]
Take that for a yes and resolve in new issues ... See #46, #45
