### ISSUE TITLE
What are the valid values in the flow data?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers#52]
@kklausmeyer 

Which data in the modeling files are the correct ones (I might have imported the wrong ones)?

Is it P10_Q, P90_Q. Estimated.Q  (I used those, not sure why)

or 

P10, P90, MEAN

I can fix that relatively quickly (but not until Friday)

**Comment by kklausmeyer** [comment]
I think the ones with the Q in them are correct.
