### ISSUE TITLE
Update documentation on https://rivers.codefornature.org/documentation.html

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers#54]
Hi Falk-  could you update the documentation for the rivers API to add some simple URL based queries for the users that are not familiar with using APIs?  

I wrote up intro text around the sample URLs you developed.  Please add this after the "introduction" section and before the "Known Issues" section.  Thank you!

[Additional_Documentation_Natural_Flows.docx](https://github.com/tnc-ca-geo/rivers/files/2049756/Additional_Documentation_Natural_Flows.docx)

**Comment by postfalk** [comment]
Ok, I will do and we should do that for completeness. Is that on someones particular request. If there is someone who wants to start to work with API we might consider officially release v2 since it is much easier and less prone to time outs.

Please let me know what the timeline. objective is.

**Comment by kklausmeyer** [comment]
This is just to make the API more accessible to a wider audience.  I have gotten feedback that the general user can't understand the more complete documentation so I wanted to provide a easy way to access the data for a single COMID.  Timeline is June 15th

**Comment by postfalk** [comment]
ok
