### ISSUE TITLE
Make edits to the Data download page (due 6/15/18)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers#55]
Add a new file for users to download.  Give it the title "Summary of Mean Monthly Unimpaired Flow Data".  Provide a description that says "Mean estimated flows (in cubic feet per second) for each month averaged over a time period from 1950 to 2015 for each stream segment identified by the COMID in the NHDPlus V2 dataset."  The data table is here N:\Projects\CA_FWA\projects\UnimparedFlows\tables\CA_data_summary_estimated_mean_1950to2015.csv.  Put this file at the top of the page, because I think it is what most users want.

**Comment by postfalk** [comment]
Are you referring to this page?

https://rivers.codefornature.org/data.html

**Comment by kklausmeyer** [comment]
Also change "XERIC" in all caps to "Xeric Region".  Change "Coast" to "Coastal Region".  Change "Mountain"  to "Mountains Region".

**Comment by kklausmeyer** [comment]
Yes that is the page I am referring to: https://rivers.codefornature.org/data.html

**Comment by postfalk** [comment]
50b47f8c47b7278a7ff0f529e284f400a8f81eb2
