### ISSUE TITLE
Prepay for AWS Hosting Service (6/20/18)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers#56]
Use up to 10K to prepay for AWS hosting fees for unimpaired flows data.  Use project number P100712 activity code 106837 for the funds.  We need this to hit this fiscal year, so there is a timeline we need to be aware of.  Thanks!

**Comment by postfalk** [comment]
@mmerrifield I would get two m4.large reservations and keep them flexible for future upgrades, which would cost 1,600 each for three years. That is about as much I could use at this point for the water program. .

**Comment by postfalk** [comment]
Did it spent $3,200 on two m4.large for three years (convertible).
